-- 011 — 헬스정보 첫 자료 (강북삼성병원 종합건진센터 2022 · 2023 · 2024)
--
--   npx wrangler d1 execute japis-db --remote --file=./migrations/011_health_seed_2022_2024.sql
--
-- 2024년 결과지 한 권에서 **세 해가 함께 나왔다.** 이 병원의 결과지는 항목마다
-- `참고범위 | 2024-09-10 | 2023-09-05 | 2022-09-06` 네 칸을 나란히 적어 준다.
-- 그래서 2024년 책 한 권을 찍는 것으로 3개년이 들어왔다 — 2022·2023년 책을 다시
-- 찍을 필요가 없다. (2021년 책을 찍으면 2019~2021 이 같은 방식으로 들어온다.)
--
-- 값은 결과지에 적힌 그대로다. 참고범위는 이름표(health_metrics)에 있는 것과
-- 같으므로 여기에서는 비워 둔다 — 병원이 바뀌어 범위가 달라지는 해가 오면
-- 그 해의 행에만 ref_low/ref_high 를 적어 넣는다(그것이 이름표를 이긴다).
--
-- 누구의 것인가: **이 포털의 첫 관리자**. 010 이 만든 표는 행마다 user_id 가 붙는다.

-- ── 검진 세 번 ────────────────────────────────────────────────────────
INSERT OR IGNORE INTO health_exams (user_id, exam_date, kind, provider, title, memo, created_at, updated_at)
  SELECT id, '2024-09-10', 'checkup', '강북삼성병원 종합건진센터', '2024년 종합건강검진',
         '종합소견 정상B · 진료가 필요한 소견 없음. LDL·총콜레스테롤 경도 상승, 공복혈당 100 이상, 요단백 약양성 추적.',
         datetime('now'), datetime('now')
    FROM users WHERE role = 'admin' ORDER BY id LIMIT 1;

INSERT OR IGNORE INTO health_exams (user_id, exam_date, kind, provider, title, memo, created_at, updated_at)
  SELECT id, '2023-09-05', 'checkup', '강북삼성병원 종합건진센터', '2023년 종합건강검진',
         '2024년 결과지의 비교 열에서 옮겨 적었다.', datetime('now'), datetime('now')
    FROM users WHERE role = 'admin' ORDER BY id LIMIT 1;

INSERT OR IGNORE INTO health_exams (user_id, exam_date, kind, provider, title, memo, created_at, updated_at)
  SELECT id, '2022-09-06', 'checkup', '강북삼성병원 종합건진센터', '2022년 종합건강검진',
         '2024년 결과지의 비교 열에서 옮겨 적었다.', datetime('now'), datetime('now')
    FROM users WHERE role = 'admin' ORDER BY id LIMIT 1;

-- 인바디 용지는 검진 결과지와 따로 나온다(체수분·부위별 근육·내장지방까지 적혀 있다).
-- '인바디·혈액' 화면이 보는 자리라 kind 를 나눠 둔다.
INSERT OR IGNORE INTO health_exams (user_id, exam_date, kind, provider, title, memo, created_at, updated_at)
  SELECT id, '2024-09-10', 'inbody', '강북삼성병원 수원종합건진센터', '2024 인바디 (InBody 73점)',
         '적정체중 67.2kg · 체중조절 +2.2kg · 지방조절 -2.5kg · 근육조절 +4.7kg',
         datetime('now'), datetime('now')
    FROM users WHERE role = 'admin' ORDER BY id LIMIT 1;

-- ── 값을 왜 JSON 한 덩어리로 넣나 ──────────────────────────────────────
-- 처음에는 `SELECT ... UNION ALL SELECT ...` 로 줄을 쌓았다. D1 은 **compound
-- SELECT 의 항 수를 아주 낮게 묶어 두어서**(열 개도 넘기지 못한다) 그 방식으로는
-- 한 회차를 못 넣는다. 그래서 `json_each()` 로 바꿨다 — 한 줄에 한 항목씩
-- [코드, 숫자, 글자] 로 적고, SQLite 가 그것을 표처럼 펼쳐 준다.
-- 사람이 읽고 고치기는 그대로이면서, 한 회차가 statement 하나로 들어간다.

-- ══════════════════════════════════════════════════════════════════════
-- 2024-09-10 종합검진
-- ══════════════════════════════════════════════════════════════════════
INSERT OR IGNORE INTO health_results (user_id, exam_id, code, value_num, value_text, created_at)
  SELECT e.user_id, e.id,
         json_extract(v.value, '$[0]'),
         json_extract(v.value, '$[1]'),
         COALESCE(json_extract(v.value, '$[2]'), ''),
         datetime('now')
    FROM health_exams e,
         json_each('[
    ["height", 174.8, null],
    ["weight", 65.0, null],
    ["bmi", 21.3, null],
    ["waist", 82.4, null],
    ["slm", 49.5, null],
    ["fatmass", 12.6, null],
    ["bodyfat", 19.3, null],
    ["fatdist", 0.83, null],
    ["sbp", 94, null],
    ["dbp", 59, null],
    ["hr", 53, null],
    ["ecg", null, "정상"],
    ["tchol", 203, null],
    ["ldl", 148, null],
    ["ldl_calc", 134, null],
    ["hdl", 50, null],
    ["tg", 94, null],
    ["ldh", 145, null],
    ["hscrp", 0.04, null],
    ["apoa1", 133, null],
    ["apob", 110, null],
    ["lpa_nmol", 142.3, null],
    ["homocysteine", 8.3, null],
    ["pwv_r", 1089, null],
    ["pwv_l", 1088, null],
    ["abi_r", 1.31, null],
    ["abi_l", 1.31, null],
    ["glucose", 101, null],
    ["hba1c", 5.8, null],
    ["insulin", 5.1, null],
    ["ft3", 2.9, null],
    ["ft4", 1.13, null],
    ["tsh", 1.77, null],
    ["metabolic", null, "정상"],
    ["tp", 6.7, null],
    ["alb", 4.4, null],
    ["glob", 2.3, null],
    ["ag", 1.91, null],
    ["ast", 17, null],
    ["alt", 12, null],
    ["alp", 51, null],
    ["ggtp", 26, null],
    ["tbil", 0.54, null],
    ["dbil", 0.21, null],
    ["idbil", 0.33, null],
    ["usg_abd", null, "정상"],
    ["hbsag", 0.315, "음성 (0.315)"],
    ["hbsab", 75.8, "양성 (75.80)"],
    ["hbcab", null, "양성"],
    ["hcvab", 0.041, "음성 (0.041)"],
    ["havab", null, "양성"],
    ["bun", 18.5, null],
    ["creatinine", 0.92, null],
    ["bc_ratio", 20.11, null],
    ["egfr_ckdepi", 95, null],
    ["u_sg", 1.03, "1.030 이상"],
    ["u_ph", 6.0, null],
    ["u_glucose", null, "음성"],
    ["u_ketone", null, "음성"],
    ["u_protein", null, "약양성"],
    ["u_bilirubin", null, "음성"],
    ["u_urobilinogen", null, "약양성"],
    ["u_nitrite", null, "음성"],
    ["u_blood", null, "음성"],
    ["u_rbc", null, "0-1"],
    ["u_wbc", null, "0-1"],
    ["u_epi", null, "0-1"],
    ["u_leu", null, "음성"],
    ["uric_acid", 3.0, null],
    ["calcium", 9.1, null],
    ["phosphorus", 3.6, null],
    ["sodium", 139, null],
    ["potassium", 4.1, null],
    ["magnesium", 2.3, null],
    ["rbc", 4.31, null],
    ["hb", 14.0, null],
    ["hct", 40.7, null],
    ["rdw", 12.4, null],
    ["ferritin", 42.8, null],
    ["iron", 129, null],
    ["tibc", 327, null],
    ["tsat", 39.45, null],
    ["mcv", 94.4, null],
    ["mch", 32.5, null],
    ["mchc", 34.4, null],
    ["platelet", 256, null],
    ["mpv", 9.6, null],
    ["pdw", 9.9, null],
    ["wbc", 5.23, null],
    ["anc", 3.17, null],
    ["neutrophil", 60.6, null],
    ["eosinophil", 2.1, null],
    ["basophil", 0.6, null],
    ["lymphocyte", 28.3, null],
    ["monocyte", 8.4, null],
    ["eos_count", 109.83, null],
    ["crp", 0.04, "음성 (0.04)"],
    ["rpr", null, "음성"],
    ["rf", null, "음성"],
    ["ana", null, "음성"],
    ["anti_ro", 0.5, "음성 (0.5)"],
    ["anti_la", 1.9, "음성 (1.9)"],
    ["testosterone", 27.0, null],
    ["fai", 57.57, null],
    ["shbg", 46.9, null],
    ["bmd_lumbar", null, "정상"],
    ["bmd_femur", null, "정상"],
    ["bmd_l1l4", 1.058, null],
    ["bmd_l1l4_t", -1.0, null],
    ["bmd_femur_tot", 0.936, null],
    ["bmd_femur_t", 0.0, null],
    ["vitd", 27.0, null],
    ["cxr", null, "정상"],
    ["fvc_l", 4.1, null],
    ["fvc_p", 90, null],
    ["fev1_l", 3.51, null],
    ["fev1_p", 97, null],
    ["fev1fvc", 86, null],
    ["pef", 9.04, null],
    ["cotinine", 0, "음성 (0)"],
    ["egd", null, "미란성위염 · 위축성위염"],
    ["occult", 0, "음성 (0)"],
    ["afp", 2.7, null],
    ["cea", 1.7, null],
    ["psa", 0.847, null],
    ["ca199", 6.0, null],
    ["nse", 10.7, null],
    ["cyfra", 1.5, null],
    ["eye_l", 1.0, null],
    ["eye_r", 0.1, null],
    ["iop_l", 11.5, null],
    ["iop_r", 12.5, null],
    ["fundus", null, "정상"],
    ["hear_l500", 10, null],
    ["hear_l1000", 15, null],
    ["hear_l2000", 10, null],
    ["hear_r500", 10, null],
    ["hear_r1000", 10, null],
    ["hear_r2000", 10, null],
    ["dental", null, "치경부마모 · 치아 표면우식 · 치주염(치석제거필요)"],
    ["stress_res", 93.8, null],
    ["ans_activity", 89.0, null],
    ["ans_balance", 0.0, null],
    ["stress_index", 93.6, null],
    ["fatigue", 108.1, null],
    ["hrv_hr", 50.8, null],
    ["cardiac_stab", 101.3, null],
    ["age_real", 52, null],
    ["age_health", 48, null],
    ["age_target", 48, null],
    ["age_cvd", 44, null],
    ["cvd_risk10", 2.79, null]
  ]') v
   WHERE e.kind = 'checkup' AND e.exam_date = '2024-09-10'
     AND e.user_id = (SELECT id FROM users WHERE role = 'admin' ORDER BY id LIMIT 1);

-- ══════════════════════════════════════════════════════════════════════
-- 2023-09-05 종합검진  (2024년 결과지의 비교 열)
-- ══════════════════════════════════════════════════════════════════════
INSERT OR IGNORE INTO health_results (user_id, exam_id, code, value_num, value_text, created_at)
  SELECT e.user_id, e.id,
         json_extract(v.value, '$[0]'),
         json_extract(v.value, '$[1]'),
         COALESCE(json_extract(v.value, '$[2]'), ''),
         datetime('now')
    FROM health_exams e,
         json_each('[
    ["height", 174.5, null],
    ["weight", 65.4, null],
    ["bmi", 21.5, null],
    ["waist", 82, null],
    ["slm", 49.5, null],
    ["fatmass", 12.9, null],
    ["bodyfat", 19.7, null],
    ["fatdist", 0.85, null],
    ["sbp", 99, null],
    ["dbp", 56, null],
    ["hr", 57, null],
    ["ecg", null, "좌측축편위"],
    ["tchol", 216, null],
    ["ldl", 162, null],
    ["ldl_calc", 149, null],
    ["hdl", 58, null],
    ["tg", 47, null],
    ["ldh", 159, null],
    ["hscrp", 0.05, null],
    ["apoa1", 137, null],
    ["apob", 112, null],
    ["lpa_nmol", 144.1, null],
    ["homocysteine", 6.7, null],
    ["pwv_r", 1116, null],
    ["pwv_l", 1037, null],
    ["abi_r", 1.24, null],
    ["abi_l", 1.18, null],
    ["carotid", null, "양측 경동맥팽대부 혈관내중막두께 증가"],
    ["glucose", 88, null],
    ["hba1c", 5.8, null],
    ["insulin", 2.9, null],
    ["ft3", 2.55, null],
    ["ft4", 1.3, null],
    ["tsh", 0.81, null],
    ["metabolic", null, "정상"],
    ["tp", 7.0, null],
    ["alb", 4.4, null],
    ["glob", 2.6, null],
    ["ag", 1.69, null],
    ["ast", 26, null],
    ["alt", 19, null],
    ["alp", 47, null],
    ["ggtp", 29, null],
    ["tbil", 0.98, null],
    ["dbil", 0.33, null],
    ["idbil", 0.65, null],
    ["usg_abd", null, "정상"],
    ["hbsag", 0.434, "음성 (0.434)"],
    ["hbsab", 81.7, "양성 (81.70)"],
    ["hbcab", null, "양성"],
    ["hcvab", 0.037, "음성 (0.037)"],
    ["havab", null, "양성"],
    ["bun", 14.4, null],
    ["creatinine", 0.86, null],
    ["bc_ratio", 16.74, null],
    ["egfr", 93, null],
    ["u_sg", 1.025, null],
    ["u_ph", 5.0, null],
    ["u_glucose", null, "음성"],
    ["u_ketone", null, "약양성"],
    ["u_protein", null, "음성"],
    ["u_bilirubin", null, "음성"],
    ["u_urobilinogen", null, "약양성"],
    ["u_nitrite", null, "음성"],
    ["u_blood", null, "음성"],
    ["u_rbc", null, "0-1"],
    ["u_wbc", null, "0-1"],
    ["u_epi", null, "0-1"],
    ["u_leu", null, "음성"],
    ["uric_acid", 3.1, null],
    ["calcium", 9.2, null],
    ["phosphorus", 3.0, null],
    ["sodium", 138, null],
    ["potassium", 4.7, null],
    ["magnesium", 2.2, null],
    ["rbc", 4.31, null],
    ["hb", 13.7, null],
    ["hct", 40.6, null],
    ["rdw", 11.9, null],
    ["ferritin", 63.8, null],
    ["iron", 196, null],
    ["tibc", 355, null],
    ["tsat", 55.21, null],
    ["mcv", 94.2, null],
    ["mch", 31.8, null],
    ["mchc", 33.7, null],
    ["platelet", 281, null],
    ["mpv", 9.3, null],
    ["pdw", 10.0, null],
    ["wbc", 5.21, null],
    ["anc", 3.24, null],
    ["neutrophil", 62.2, null],
    ["eosinophil", 1.0, null],
    ["basophil", 0.4, null],
    ["lymphocyte", 27.8, null],
    ["monocyte", 8.6, null],
    ["eos_count", 52.1, null],
    ["crp", 0.05, "음성 (0.05)"],
    ["rpr", null, "음성"],
    ["rf", null, "음성"],
    ["vitd", 29.5, null],
    ["cxr", null, "정상"],
    ["fvc_l", 4.25, null],
    ["fvc_p", 91, null],
    ["fev1_l", 3.58, null],
    ["fev1_p", 104, null],
    ["fev1fvc", 84.22, null],
    ["pef", 9.24, null],
    ["cotinine", 0, "음성 (0)"],
    ["egd", null, "미란성위염 · 위축성위염"],
    ["colono", null, "정상"],
    ["occult", null, "검사안함"],
    ["afp", 3.2, null],
    ["cea", 1.4, null],
    ["psa", 0.743, null],
    ["ca199", 6.5, null],
    ["nse", 11.0, null],
    ["cyfra", 0.7, null],
    ["eye_l", 0.7, null],
    ["eye_r", 0.2, null],
    ["iop_l", 10, null],
    ["iop_r", 12.5, null],
    ["fundus", null, "정상"],
    ["hear_l500", 10, null],
    ["hear_l1000", 15, null],
    ["hear_l2000", 10, null],
    ["hear_r500", 10, null],
    ["hear_r1000", 10, null],
    ["hear_r2000", 5, null],
    ["dental", null, "치석(치석제거필요) · 치아우식증 · 치경부마모"],
    ["stress_res", 93.2, null],
    ["ans_activity", 90.4, null],
    ["ans_balance", 90.0, null],
    ["age_real", 51, null],
    ["age_health", 48, null],
    ["age_target", 48, null]
  ]') v
   WHERE e.kind = 'checkup' AND e.exam_date = '2023-09-05'
     AND e.user_id = (SELECT id FROM users WHERE role = 'admin' ORDER BY id LIMIT 1);

-- ══════════════════════════════════════════════════════════════════════
-- 2022-09-06 종합검진  (2024년 결과지의 비교 열)
-- ══════════════════════════════════════════════════════════════════════
INSERT OR IGNORE INTO health_results (user_id, exam_id, code, value_num, value_text, created_at)
  SELECT e.user_id, e.id,
         json_extract(v.value, '$[0]'),
         json_extract(v.value, '$[1]'),
         COALESCE(json_extract(v.value, '$[2]'), ''),
         datetime('now')
    FROM health_exams e,
         json_each('[
    ["height", 174.9, null],
    ["weight", 66.1, null],
    ["bmi", 21.6, null],
    ["waist", 84.4, null],
    ["slm", 50.1, null],
    ["fatmass", 13, null],
    ["bodyfat", 19.6, null],
    ["fatdist", 0.86, null],
    ["sbp", 103, null],
    ["dbp", 60, null],
    ["hr", 55, null],
    ["ecg", null, "정상"],
    ["echo", null, "정상"],
    ["tchol", 229, null],
    ["ldl", 171, null],
    ["ldl_calc", 155, null],
    ["hdl", 56, null],
    ["tg", 89, null],
    ["ldh", 160, null],
    ["hscrp", 0.05, null],
    ["apoa1", 148, null],
    ["apob", 124, null],
    ["lpa_mg", 69.7, null],
    ["homocysteine", 8.7, null],
    ["ntprobnp", 21, null],
    ["pwv_r", 1070, null],
    ["pwv_l", 1102, null],
    ["abi_r", 1.25, null],
    ["abi_l", 1.24, null],
    ["tcd", null, "특이소견없음"],
    ["glucose", 96, null],
    ["hba1c", 6.0, null],
    ["insulin", 3.6, null],
    ["ft3", 2.95, null],
    ["ft4", 1.14, null],
    ["tsh", 1.17, null],
    ["metabolic", null, "정상"],
    ["tp", 7.2, null],
    ["alb", 4.5, null],
    ["glob", 2.7, null],
    ["ag", 1.67, null],
    ["ast", 18, null],
    ["alt", 15, null],
    ["alp", 49, null],
    ["ggtp", 29, null],
    ["tbil", 0.57, null],
    ["dbil", 0.21, null],
    ["idbil", 0.36, null],
    ["usg_abd", null, "지방간 경증"],
    ["hbsag", 0.459, "음성 (0.459)"],
    ["hbsab", 84.1, "양성 (84.10)"],
    ["hbcab", null, "양성"],
    ["hcvab", 0.039, "음성 (0.039)"],
    ["havab", null, "양성"],
    ["bun", 16.3, null],
    ["creatinine", 1.0, null],
    ["bc_ratio", 16.3, null],
    ["egfr", 79, null],
    ["u_sg", 1.025, null],
    ["u_ph", 6.5, null],
    ["u_glucose", null, "음성"],
    ["u_ketone", null, "음성"],
    ["u_protein", null, "음성"],
    ["u_bilirubin", null, "음성"],
    ["u_urobilinogen", null, "약양성"],
    ["u_nitrite", null, "음성"],
    ["u_blood", null, "음성"],
    ["u_rbc", null, "0-1"],
    ["u_wbc", null, "0-1"],
    ["u_epi", null, "0-1"],
    ["u_leu", null, "음성"],
    ["uric_acid", 3.5, null],
    ["calcium", 9.3, null],
    ["phosphorus", 3.6, null],
    ["sodium", 141, null],
    ["potassium", 4.9, null],
    ["magnesium", 2.4, null],
    ["rbc", 4.42, null],
    ["hb", 14.2, null],
    ["hct", 41.2, null],
    ["rdw", 11.9, null],
    ["ferritin", 108.0, null],
    ["iron", 86, null],
    ["tibc", 327, null],
    ["tsat", 26.3, null],
    ["mcv", 93.2, null],
    ["mch", 32.1, null],
    ["mchc", 34.5, null],
    ["platelet", 257, null],
    ["mpv", 9.3, null],
    ["pdw", 10.6, null],
    ["wbc", 5.6, null],
    ["anc", 3.48, null],
    ["neutrophil", 62.2, null],
    ["eosinophil", 1.6, null],
    ["basophil", 0.5, null],
    ["lymphocyte", 28.2, null],
    ["monocyte", 7.5, null],
    ["eos_count", 89.6, null],
    ["crp", 0.05, "음성 (0.05)"],
    ["rpr", null, "음성"],
    ["rf", null, "음성"],
    ["vitd", 28.4, null],
    ["cxr", null, "정상"],
    ["cotinine", 0, "음성 (0)"],
    ["egd", null, "위축성위염 · 위점막미란"],
    ["occult", 3, "음성 (3)"],
    ["petct", null, "특이소견없음"],
    ["afp", 3.3, null],
    ["cea", 1.4, null],
    ["psa", 0.752, null],
    ["ca199", 7.0, null],
    ["nse", 12.1, null],
    ["cyfra", 1.0, null],
    ["eye_l", 0.8, null],
    ["eye_r", 0.2, null],
    ["iop_l", 10, null],
    ["iop_r", 10.5, null],
    ["fundus", null, "정상"],
    ["hear_l500", 10, null],
    ["hear_l1000", 15, null],
    ["hear_l2000", 10, null],
    ["hear_r500", 5, null],
    ["hear_r1000", 10, null],
    ["hear_r2000", 5, null],
    ["dental", null, "치경부 마모증(치료권장) · 치석(치석제거필요) · 식편압입"],
    ["stress_res", 92.2, null],
    ["ans_activity", 84.3, null],
    ["ans_balance", 83.3, null],
    ["age_real", 50, null],
    ["age_health", 48, null],
    ["age_target", 48, null]
  ]') v
   WHERE e.kind = 'checkup' AND e.exam_date = '2022-09-06'
     AND e.user_id = (SELECT id FROM users WHERE role = 'admin' ORDER BY id LIMIT 1);

-- ══════════════════════════════════════════════════════════════════════
-- 2024-09-10 인바디  (InBody 용지 — 검진 결과지에는 없는 칸까지)
-- ══════════════════════════════════════════════════════════════════════
INSERT OR IGNORE INTO health_results (user_id, exam_id, code, value_num, value_text, created_at)
  SELECT e.user_id, e.id,
         json_extract(v.value, '$[0]'),
         json_extract(v.value, '$[1]'),
         COALESCE(json_extract(v.value, '$[2]'), ''),
         datetime('now')
    FROM health_exams e,
         json_each('[
    ["height", 174.8, null],
    ["weight", 65.0, null],
    ["bmi", 21.3, null],
    ["slm", 49.5, null],
    ["smm", 29.4, null],
    ["fatmass", 12.6, null],
    ["bodyfat", 19.3, null],
    ["fatdist", 0.83, null],
    ["ffm", 52.4, null],
    ["tbw", 38.5, null],
    ["protein", 10.4, null],
    ["mineral_mass", 3.53, null],
    ["vfa", 49.1, null],
    ["ecw", 0.375, null],
    ["bmr", 1503, null],
    ["inbody_score", 73, null],
    ["obesity_deg", 97, null]
  ]') v
   WHERE e.kind = 'inbody' AND e.exam_date = '2024-09-10'
     AND e.user_id = (SELECT id FROM users WHERE role = 'admin' ORDER BY id LIMIT 1);
