-- 014 — 2021년 결과지 한 권에서 나온 2017 ~ 2021
--
--   npx wrangler d1 execute japis-db --remote --file=./migrations/014_health_2017_2021.sql
--
-- ── 한 권에 네 해 ──────────────────────────────────────────────────────
--
-- 2021년 강북삼성 결과지는 비교 열이 **다섯 칸**이다
-- (2021-09-16 · 2020-09-17 · 2019-08-08 · 2018-10-16 · 2018-07-12).
-- 책 한 권을 찍는 것으로 네 번의 검진이 들어왔다. 그리고 앞쪽의
-- '연도별 주요건강 지표' 그래프에는 **2017-07** 까지 그려져 있어, 거기서
-- 열 항목을 더 옮겨 적었다(아래 2017 회차의 메모 참고).
--
-- ── 2018년은 두 번이다 ─────────────────────────────────────────────────
-- 2018-10-16 은 종합검진이 아니라 **재검**이다. 혈당·당화혈색소와 소변검사
-- 열몇 줄뿐이다. 그래도 회차로 세워 둔다 — 그 해 7월의 공복혈당 108 이
-- 석 달 뒤 100 으로 내려온 것은 한 해에 한 점만 찍어서는 보이지 않는다.
--
-- ── 참고범위 ───────────────────────────────────────────────────────────
-- 같은 강북삼성이라 이름표(010)의 범위와 거의 같다. 이 책이 다르게 적은
-- 셋만 행에 담는다 — 혈소판(160~362) · APO 지단백 B(63~160) · 맥파전파속도(0~1360).

-- ── 새 검사항목 이름표 ────────────────────────────────────────────────
INSERT OR REPLACE INTO health_metrics
  (code, name_ko, name_en, unit, category, sort_order, ref_low, ref_high, ref_text, direction, value_type, lab_group, memo)
VALUES
('ct_brain',  '뇌CT',                  'Brain CT (non-contrast)',   '', 'lipid',  192, NULL, NULL, '', 'none', 'text', NULL, ''),
('cac_mdct',  '관상동맥 석회화 MDCT',  'Coronary calcium scoring',  '', 'bp',      45, NULL, NULL, '', 'none', 'text', NULL, '심장 혈관에 석회가 끼었는지'),
('cvd_grade', '관상동맥질환 위험도',   'Cardiovascular risk grade', '', 'bp',      46, NULL, NULL, '', 'none', 'text', NULL, '');

-- ══════════════════════════════════════════════════════════════════════
-- 2021-09-16 종합검진 — 강북삼성병원 수원종합건진센터
-- ══════════════════════════════════════════════════════════════════════
INSERT OR IGNORE INTO health_exams (user_id, exam_date, kind, provider, title, memo, created_at, updated_at)
  SELECT id, '2021-09-16', 'checkup', '강북삼성병원 수원종합건진센터', '2021년 종합건강검진',
         '판정: 총콜레스테롤·LDL 경도 상승 · HDL 낮음 · 지단백(a) 상승 · 공복혈당장애 · 당화혈색소 6.0 · 비타민D 14.5 부족 · 요잠혈 양성(1+) · 치주염(치석제거 필요).', datetime('now'), datetime('now')
    FROM users WHERE role = 'admin' ORDER BY id LIMIT 1;

INSERT OR IGNORE INTO health_results
  (user_id, exam_id, code, value_num, value_text, ref_low, ref_high, ref_text, created_at)
  SELECT e.user_id, e.id,
         json_extract(v.value, '$[0]'),
         json_extract(v.value, '$[1]'),
         COALESCE(json_extract(v.value, '$[2]'), ''),
         json_extract(v.value, '$[3]'),
         json_extract(v.value, '$[4]'),
         COALESCE(json_extract(v.value, '$[5]'), ''),
         datetime('now')
    FROM health_exams e,
         json_each('[
    ["egd", null, "만성표재성위염 · 위점막미란 · 위황색종", null, null, ""],
    ["occult", 0, "음성 (0)", null, null, ""],
    ["usg_pelvis", null, "정상 (전립선)", null, null, ""],
    ["afp", 3.1, null, null, null, ""],
    ["cea", 1.7, null, null, null, ""],
    ["psa", 0.757, null, null, null, ""],
    ["ca199", 6.4, null, null, null, ""],
    ["nse", 11.6, null, null, null, ""],
    ["cyfra", 1.3, null, null, null, ""],
    ["usg_abd", null, "정상", null, null, ""],
    ["tp", 7.0, null, null, null, ""],
    ["alb", 4.4, null, null, null, ""],
    ["glob", 2.6, null, null, null, ""],
    ["ag", 1.69, null, null, null, ""],
    ["ast", 18, null, null, null, ""],
    ["alt", 16, null, null, null, ""],
    ["alp", 48, null, null, null, ""],
    ["ggtp", 30, null, null, null, ""],
    ["tbil", 0.74, null, null, null, ""],
    ["dbil", 0.25, null, null, null, ""],
    ["idbil", 0.49, null, null, null, ""],
    ["hbsag", 0.32, "음성 (0.32)", null, null, ""],
    ["hbsab", 102.0, "양성 (102.00)", null, null, ""],
    ["hbcab", null, "양성", null, null, ""],
    ["hcvab", 0.03, "음성 (0.03)", null, null, ""],
    ["havab", null, "양성", null, null, ""],
    ["cxr", null, "정상", null, null, ""],
    ["cotinine", 0, "음성 (0)", null, null, ""],
    ["sbp", 103, null, null, null, ""],
    ["dbp", 62, null, null, null, ""],
    ["hr", 48, null, null, null, ""],
    ["ecg", null, "서맥", null, null, ""],
    ["ct_brain", null, "정상", null, null, ""],
    ["tchol", 222, null, null, null, ""],
    ["ldl", 165, null, null, null, ""],
    ["ldl_calc", 155, null, null, null, ""],
    ["hdl", 50, null, null, null, ""],
    ["tg", 83, null, null, null, ""],
    ["ldh", 176, null, null, null, ""],
    ["hscrp", 0.06, null, null, null, ""],
    ["apoa1", 143, null, null, null, ""],
    ["apob", 123, null, 63, 160, "63~160"],
    ["lpa_mg", 63.1, null, null, null, ""],
    ["homocysteine", 10.7, null, null, null, ""],
    ["pwv_r", 1068, null, 0, 1360, "0~1360"],
    ["pwv_l", 1042, null, 0, 1360, "0~1360"],
    ["abi_r", 1.21, null, null, null, ""],
    ["abi_l", 1.19, null, null, null, ""],
    ["glucose", 101, null, null, null, ""],
    ["hba1c", 6.0, null, null, null, ""],
    ["insulin", 7.1, null, null, null, ""],
    ["ft3", 3.12, null, null, null, ""],
    ["ft4", 1.23, null, null, null, ""],
    ["tsh", 1.29, null, null, null, ""],
    ["metabolic", null, "정상", null, null, ""],
    ["bun", 14.6, null, null, null, ""],
    ["creatinine", 0.88, null, null, null, ""],
    ["bc_ratio", 16.59, null, null, null, ""],
    ["egfr", 92, null, null, null, ""],
    ["u_sg", 1.015, null, null, null, ""],
    ["u_ph", 5.5, null, null, null, ""],
    ["u_glucose", null, "음성", null, null, ""],
    ["u_ketone", null, "음성", null, null, ""],
    ["u_protein", null, "음성", null, null, ""],
    ["u_bilirubin", null, "음성", null, null, ""],
    ["u_urobilinogen", null, "약양성", null, null, ""],
    ["u_nitrite", null, "음성", null, null, ""],
    ["u_blood", null, "양성 (1+)", null, null, ""],
    ["u_rbc", null, "1-3", null, null, ""],
    ["u_wbc", null, "0-1", null, null, ""],
    ["u_epi", null, "0-1", null, null, ""],
    ["u_leu", null, "음성", null, null, ""],
    ["uric_acid", 3.4, null, null, null, ""],
    ["calcium", 9.2, null, null, null, ""],
    ["phosphorus", 3.4, null, null, null, ""],
    ["sodium", 139, null, null, null, ""],
    ["potassium", 4.6, null, null, null, ""],
    ["magnesium", 2.1, null, null, null, ""],
    ["rbc", 4.62, null, null, null, ""],
    ["hb", 14.5, null, null, null, ""],
    ["hct", 42.1, null, null, null, ""],
    ["rdw", 12.0, null, null, null, ""],
    ["ferritin", 184.0, null, null, null, ""],
    ["iron", 128, null, null, null, ""],
    ["tibc", 288, null, null, null, ""],
    ["tsat", 44.44, null, null, null, ""],
    ["mcv", 91.1, null, null, null, ""],
    ["mch", 31.4, null, null, null, ""],
    ["mchc", 34.4, null, null, null, ""],
    ["platelet", 278, null, 160, 362, "160~362"],
    ["mpv", 9.7, null, null, null, ""],
    ["pdw", 9.9, null, null, null, ""],
    ["wbc", 5.56, null, null, null, ""],
    ["anc", 3.53, null, null, null, ""],
    ["neutrophil", 63.6, null, null, null, ""],
    ["eosinophil", 1.4, null, null, null, ""],
    ["basophil", 0.9, null, null, null, ""],
    ["lymphocyte", 25.5, null, null, null, ""],
    ["monocyte", 8.6, null, null, null, ""],
    ["eos_count", 77.84, null, null, null, ""],
    ["crp", 0.04, "음성 (0.04)", null, null, ""],
    ["rpr", null, "음성", null, null, ""],
    ["rf", null, "음성", null, null, ""],
    ["vitd", 14.5, null, null, null, ""],
    ["height", 174.8, null, null, null, ""],
    ["weight", 67.7, null, null, null, ""],
    ["bmi", 22.2, null, null, null, ""],
    ["waist", 83.6, null, null, null, ""],
    ["slm", 50.8, null, null, null, ""],
    ["fatmass", 13.9, null, null, null, ""],
    ["bodyfat", 20.5, null, null, null, ""],
    ["fatdist", 0.86, null, null, null, ""],
    ["eye_l", 0.8, null, null, null, ""],
    ["eye_r", 0.1, null, null, null, ""],
    ["iop_l", 11, null, null, null, ""],
    ["iop_r", 13, null, null, null, ""],
    ["fundus", null, "정상", null, null, ""],
    ["hear_l500", 10, null, null, null, ""],
    ["hear_l1000", 15, null, null, null, ""],
    ["hear_l2000", 10, null, null, null, ""],
    ["hear_r500", 5, null, null, null, ""],
    ["hear_r1000", 5, null, null, null, ""],
    ["hear_r2000", 10, null, null, null, ""],
    ["dental", null, "치주염(치석제거필요) · 치아 표면우식", null, null, ""],
    ["stress_res", 113.9, null, null, null, ""],
    ["ans_activity", 110.3, null, null, null, ""],
    ["ans_balance", 75.0, null, null, null, ""],
    ["stress_index", 72.4, null, null, null, ""],
    ["fatigue", 99.0, null, null, null, ""],
    ["hrv_hr", 50.8, null, null, null, ""],
    ["cardiac_stab", 130.1, null, null, null, ""],
    ["age_real", 49, null, null, null, ""],
    ["age_health", 44, null, null, null, ""],
    ["age_target", 44, null, null, null, ""]
  ]') v
   WHERE e.kind = 'checkup' AND e.exam_date = '2021-09-16'
     AND e.user_id = (SELECT id FROM users WHERE role = 'admin' ORDER BY id LIMIT 1);

-- ══════════════════════════════════════════════════════════════════════
-- 2020-09-17 종합검진
-- ══════════════════════════════════════════════════════════════════════
INSERT OR IGNORE INTO health_exams (user_id, exam_date, kind, provider, title, memo, created_at, updated_at)
  SELECT id, '2020-09-17', 'checkup', '강북삼성병원 수원종합건진센터', '2020년 종합건강검진',
         '2021년 결과지의 비교 열에서 옮겨 적었다. 관상동맥 석회화 MDCT 정상 · 저위험군 · HDL 46 낮음 · 비타민D 14.0 부족.', datetime('now'), datetime('now')
    FROM users WHERE role = 'admin' ORDER BY id LIMIT 1;

INSERT OR IGNORE INTO health_results
  (user_id, exam_id, code, value_num, value_text, ref_low, ref_high, ref_text, created_at)
  SELECT e.user_id, e.id,
         json_extract(v.value, '$[0]'),
         json_extract(v.value, '$[1]'),
         COALESCE(json_extract(v.value, '$[2]'), ''),
         json_extract(v.value, '$[3]'),
         json_extract(v.value, '$[4]'),
         COALESCE(json_extract(v.value, '$[5]'), ''),
         datetime('now')
    FROM health_exams e,
         json_each('[
    ["egd", null, "미란성위염 · 위축성위염", null, null, ""],
    ["occult", null, "검사안함", null, null, ""],
    ["usg_thyroid", null, "정상", null, null, ""],
    ["afp", 2.9, null, null, null, ""],
    ["cea", 1.3, null, null, null, ""],
    ["psa", 0.686, null, null, null, ""],
    ["ca199", 6.2, null, null, null, ""],
    ["nse", 11.4, null, null, null, ""],
    ["cyfra", 0.7, null, null, null, ""],
    ["usg_abd", null, "정상", null, null, ""],
    ["tp", 6.8, null, null, null, ""],
    ["alb", 4.3, null, null, null, ""],
    ["glob", 2.5, null, null, null, ""],
    ["ag", 1.72, null, null, null, ""],
    ["ast", 16, null, null, null, ""],
    ["alt", 11, null, null, null, ""],
    ["alp", 43, null, null, null, ""],
    ["ggtp", 25, null, null, null, ""],
    ["tbil", 0.72, null, null, null, ""],
    ["dbil", 0.24, null, null, null, ""],
    ["idbil", 0.48, null, null, null, ""],
    ["hbsag", 0.33, "음성 (0.33)", null, null, ""],
    ["hbsab", 73.7, "양성 (73.70)", null, null, ""],
    ["hbcab", null, "양성", null, null, ""],
    ["hcvab", 0.04, "음성 (0.04)", null, null, ""],
    ["havab", null, "양성", null, null, ""],
    ["cxr", null, "정상", null, null, ""],
    ["cotinine", 0, "음성 (0)", null, null, ""],
    ["sbp", 100, null, null, null, ""],
    ["dbp", 66, null, null, null, ""],
    ["hr", 58, null, null, null, ""],
    ["ecg", null, "다발성심실조기수축", null, null, ""],
    ["cac_mdct", null, "정상", null, null, ""],
    ["cvd_grade", null, "저위험군 (Very low)", null, null, ""],
    ["tchol", 198, null, null, null, ""],
    ["ldl", 141, null, null, null, ""],
    ["ldl_calc", 131, null, null, null, ""],
    ["hdl", 46, null, null, null, ""],
    ["tg", 106, null, null, null, ""],
    ["ldh", 171, null, null, null, ""],
    ["hscrp", 0.05, null, null, null, ""],
    ["apoa1", 128, null, null, null, ""],
    ["apob", 111, null, 63, 160, "63~160"],
    ["lpa_mg", 58.1, null, null, null, ""],
    ["homocysteine", 10.7, null, null, null, ""],
    ["pwv_r", 1151, null, 0, 1360, "0~1360"],
    ["pwv_l", 1119, null, 0, 1360, "0~1360"],
    ["abi_r", 1.33, null, null, null, ""],
    ["abi_l", 1.22, null, null, null, ""],
    ["glucose", 97, null, null, null, ""],
    ["hba1c", 6.0, null, null, null, ""],
    ["insulin", 6.9, null, null, null, ""],
    ["ft3", 2.82, null, null, null, ""],
    ["ft4", 1.09, null, null, null, ""],
    ["tsh", 2.39, null, null, null, ""],
    ["metabolic", null, "정상", null, null, ""],
    ["bun", 13.5, null, null, null, ""],
    ["creatinine", 0.94, null, null, null, ""],
    ["bc_ratio", 14.36, null, null, null, ""],
    ["egfr", 85, null, null, null, ""],
    ["u_sg", 1.01, null, null, null, ""],
    ["u_ph", 5.5, null, null, null, ""],
    ["u_glucose", null, "음성", null, null, ""],
    ["u_ketone", null, "음성", null, null, ""],
    ["u_protein", null, "음성", null, null, ""],
    ["u_bilirubin", null, "음성", null, null, ""],
    ["u_urobilinogen", null, "약양성", null, null, ""],
    ["u_nitrite", null, "음성", null, null, ""],
    ["u_blood", null, "음성", null, null, ""],
    ["u_rbc", null, "0-1", null, null, ""],
    ["u_wbc", null, "0-1", null, null, ""],
    ["u_epi", null, "0-1", null, null, ""],
    ["u_leu", null, "음성", null, null, ""],
    ["uric_acid", 3.5, null, null, null, ""],
    ["calcium", 9.0, null, null, null, ""],
    ["phosphorus", 3.6, null, null, null, ""],
    ["sodium", 139, null, null, null, ""],
    ["potassium", 4.4, null, null, null, ""],
    ["magnesium", 2.2, null, null, null, ""],
    ["rbc", 4.52, null, null, null, ""],
    ["hb", 14.5, null, null, null, ""],
    ["hct", 41.9, null, null, null, ""],
    ["rdw", 12.7, null, null, null, ""],
    ["ferritin", 130.0, null, null, null, ""],
    ["iron", 101, null, null, null, ""],
    ["tibc", 295, null, null, null, ""],
    ["tsat", 34.24, null, null, null, ""],
    ["mcv", 92.7, null, null, null, ""],
    ["mch", 32.1, null, null, null, ""],
    ["mchc", 34.6, null, null, null, ""],
    ["platelet", 287, null, 160, 362, "160~362"],
    ["mpv", 9.8, null, null, null, ""],
    ["pdw", 11.5, null, null, null, ""],
    ["wbc", 5.36, null, null, null, ""],
    ["anc", 3.32, null, null, null, ""],
    ["neutrophil", 61.8, null, null, null, ""],
    ["eosinophil", 1.9, null, null, null, ""],
    ["basophil", 0.6, null, null, null, ""],
    ["lymphocyte", 28.2, null, null, null, ""],
    ["monocyte", 7.5, null, null, null, ""],
    ["eos_count", 101.84, null, null, null, ""],
    ["crp", 0.05, "음성 (0.05)", null, null, ""],
    ["rpr", null, "음성", null, null, ""],
    ["rf", null, "음성", null, null, ""],
    ["vitd", 14.0, null, null, null, ""],
    ["height", 175.3, null, null, null, ""],
    ["weight", 66.6, null, null, null, ""],
    ["bmi", 21.7, null, null, null, ""],
    ["waist", 83.1, null, null, null, ""],
    ["slm", 50.2, null, null, null, ""],
    ["fatmass", 13.4, null, null, null, ""],
    ["bodyfat", 20.2, null, null, null, ""],
    ["fatdist", 0.86, null, null, null, ""],
    ["eye_l", 0.7, null, null, null, ""],
    ["eye_r", 0.1, null, null, null, ""],
    ["iop_l", 12.5, null, null, null, ""],
    ["iop_r", 12, null, null, null, ""],
    ["fundus", null, "정상", null, null, ""],
    ["hear_l500", 10, null, null, null, ""],
    ["hear_l1000", 15, null, null, null, ""],
    ["hear_l2000", 10, null, null, null, ""],
    ["hear_r500", 5, null, null, null, ""],
    ["hear_r1000", 5, null, null, null, ""],
    ["hear_r2000", 5, null, null, null, ""],
    ["dental", null, "치경부 마모증(치료권장) · 치아 표면우식 · 치석(치석제거필요)", null, null, ""],
    ["stress_res", 108.3, null, null, null, ""],
    ["ans_activity", 106.4, null, null, null, ""],
    ["ans_balance", 58.3, null, null, null, ""],
    ["age_real", 48, null, null, null, ""],
    ["age_health", 44, null, null, null, ""],
    ["age_target", 44, null, null, null, ""]
  ]') v
   WHERE e.kind = 'checkup' AND e.exam_date = '2020-09-17'
     AND e.user_id = (SELECT id FROM users WHERE role = 'admin' ORDER BY id LIMIT 1);

-- ══════════════════════════════════════════════════════════════════════
-- 2019-08-08 종합검진
-- ══════════════════════════════════════════════════════════════════════
INSERT OR IGNORE INTO health_exams (user_id, exam_date, kind, provider, title, memo, created_at, updated_at)
  SELECT id, '2019-08-08', 'checkup', '강북삼성병원 수원종합건진센터', '2019년 종합건강검진',
         '2021년 결과지의 비교 열에서 옮겨 적었다. 이 기간 중 총콜레스테롤(181)·LDL(126)이 가장 낮았던 해. 철 217 높음 · 심장초음파 삼첨판막 역류(경도) · 비타민D 17.8 부족.', datetime('now'), datetime('now')
    FROM users WHERE role = 'admin' ORDER BY id LIMIT 1;

INSERT OR IGNORE INTO health_results
  (user_id, exam_id, code, value_num, value_text, ref_low, ref_high, ref_text, created_at)
  SELECT e.user_id, e.id,
         json_extract(v.value, '$[0]'),
         json_extract(v.value, '$[1]'),
         COALESCE(json_extract(v.value, '$[2]'), ''),
         json_extract(v.value, '$[3]'),
         json_extract(v.value, '$[4]'),
         COALESCE(json_extract(v.value, '$[5]'), ''),
         datetime('now')
    FROM health_exams e,
         json_each('[
    ["egd", null, "위축성위염 · 미란성위염", null, null, ""],
    ["occult", null, "검사안함", null, null, ""],
    ["afp", 2.8, null, null, null, ""],
    ["cea", 1.6, null, null, null, ""],
    ["psa", 0.743, null, null, null, ""],
    ["ca199", 7.6, null, null, null, ""],
    ["nse", 11.9, null, null, null, ""],
    ["cyfra", 0.8, null, null, null, ""],
    ["usg_abd", null, "정상", null, null, ""],
    ["tp", 6.7, null, null, null, ""],
    ["alb", 4.2, null, null, null, ""],
    ["glob", 2.5, null, null, null, ""],
    ["ag", 1.68, null, null, null, ""],
    ["ast", 16, null, null, null, ""],
    ["alt", 13, null, null, null, ""],
    ["alp", 46, null, null, null, ""],
    ["ggtp", 25, null, null, null, ""],
    ["tbil", 0.93, null, null, null, ""],
    ["dbil", 0.33, null, null, null, ""],
    ["idbil", 0.6, null, null, null, ""],
    ["hbsag", 0.46, "음성 (0.46)", null, null, ""],
    ["hbsab", 68.3, "양성 (68.30)", null, null, ""],
    ["hbcab", null, "양성", null, null, ""],
    ["hcvab", 0.04, "음성 (0.04)", null, null, ""],
    ["havab", null, "양성", null, null, ""],
    ["cxr", null, "정상", null, null, ""],
    ["fvc_l", 4.52, null, null, null, ""],
    ["fvc_p", 94.14, null, null, null, ""],
    ["fev1_l", 3.77, null, null, null, ""],
    ["fev1_p", 104.49, null, null, null, ""],
    ["fev1fvc", 83.3, null, null, null, ""],
    ["pef", 10.36, null, null, null, ""],
    ["cotinine", 0, "음성 (0)", null, null, ""],
    ["sbp", 115, null, null, null, ""],
    ["dbp", 60, null, null, null, ""],
    ["hr", 53, null, null, null, ""],
    ["ecg", null, "심실조기수축", null, null, ""],
    ["echo", null, "삼첨판막 역류 (경도)", null, null, ""],
    ["tcd", null, "특이소견없음", null, null, ""],
    ["tchol", 181, null, null, null, ""],
    ["ldl", 126, null, null, null, ""],
    ["ldl_calc", 109, null, null, null, ""],
    ["hdl", 45, null, null, null, ""],
    ["tg", 134, null, null, null, ""],
    ["ldh", 177, null, null, null, ""],
    ["hscrp", 0.03, null, null, null, ""],
    ["apoa1", 125, null, null, null, ""],
    ["apob", 99, null, 63, 160, "63~160"],
    ["lpa_mg", 52.5, null, null, null, ""],
    ["homocysteine", 8.0, null, null, null, ""],
    ["pwv_r", 1159, null, 0, 1360, "0~1360"],
    ["pwv_l", 1070, null, 0, 1360, "0~1360"],
    ["abi_r", 1.22, null, null, null, ""],
    ["abi_l", 1.21, null, null, null, ""],
    ["glucose", 104, null, null, null, ""],
    ["hba1c", 5.8, null, null, null, ""],
    ["insulin", 5.2, null, null, null, ""],
    ["ft3", 2.9, null, null, null, ""],
    ["ft4", 1.16, null, null, null, ""],
    ["tsh", 1.45, null, null, null, ""],
    ["metabolic", null, "정상", null, null, ""],
    ["bun", 15.2, null, null, null, ""],
    ["creatinine", 1.02, null, null, null, ""],
    ["bc_ratio", 14.9, null, null, null, ""],
    ["egfr", 78, null, null, null, ""],
    ["u_sg", 1.025, null, null, null, ""],
    ["u_ph", 5.5, null, null, null, ""],
    ["u_glucose", null, "음성", null, null, ""],
    ["u_ketone", null, "음성", null, null, ""],
    ["u_protein", null, "음성", null, null, ""],
    ["u_bilirubin", null, "음성", null, null, ""],
    ["u_urobilinogen", null, "약양성", null, null, ""],
    ["u_nitrite", null, "음성", null, null, ""],
    ["u_blood", null, "음성", null, null, ""],
    ["u_rbc", null, "0-1", null, null, ""],
    ["u_wbc", null, "0-1", null, null, ""],
    ["u_epi", null, "0-1", null, null, ""],
    ["u_leu", null, "음성", null, null, ""],
    ["uric_acid", 3.5, null, null, null, ""],
    ["calcium", 8.8, null, null, null, ""],
    ["phosphorus", 3.4, null, null, null, ""],
    ["sodium", 141, null, null, null, ""],
    ["potassium", 4.2, null, null, null, ""],
    ["magnesium", 2.2, null, null, null, ""],
    ["rbc", 4.44, null, null, null, ""],
    ["hb", 14.2, null, null, null, ""],
    ["hct", 41.7, null, null, null, ""],
    ["rdw", 12.9, null, null, null, ""],
    ["ferritin", 77.1, null, null, null, ""],
    ["iron", 217, null, null, null, ""],
    ["tibc", 292, null, null, null, ""],
    ["tsat", 74.32, null, null, null, ""],
    ["mcv", 93.9, null, null, null, ""],
    ["mch", 32.0, null, null, null, ""],
    ["mchc", 34.1, null, null, null, ""],
    ["platelet", 276, null, 160, 362, "160~362"],
    ["mpv", 10.0, null, null, null, ""],
    ["pdw", 11.4, null, null, null, ""],
    ["wbc", 5.56, null, null, null, ""],
    ["anc", 3.43, null, null, null, ""],
    ["neutrophil", 61.6, null, null, null, ""],
    ["eosinophil", 2.2, null, null, null, ""],
    ["basophil", 0.5, null, null, null, ""],
    ["lymphocyte", 26.3, null, null, null, ""],
    ["monocyte", 9.4, null, null, null, ""],
    ["eos_count", 122.32, null, null, null, ""],
    ["crp", 0.03, "음성 (0.03)", null, null, ""],
    ["rpr", null, "음성", null, null, ""],
    ["rf", null, "음성", null, null, ""],
    ["vitd", 17.8, null, null, null, ""],
    ["height", 175.2, null, null, null, ""],
    ["weight", 68.1, null, null, null, ""],
    ["bmi", 22.2, null, null, null, ""],
    ["waist", 86, null, null, null, ""],
    ["slm", 51.6, null, null, null, ""],
    ["fatmass", 13.4, null, null, null, ""],
    ["bodyfat", 19.7, null, null, null, ""],
    ["fatdist", 0.86, null, null, null, ""],
    ["eye_l", 0.7, null, null, null, ""],
    ["eye_r", 0.2, null, null, null, ""],
    ["iop_l", 13.5, null, null, null, ""],
    ["iop_r", 11.5, null, null, null, ""],
    ["fundus", null, "정상", null, null, ""],
    ["hear_l500", 5, null, null, null, ""],
    ["hear_l1000", 10, null, null, null, ""],
    ["hear_l2000", 5, null, null, null, ""],
    ["hear_r500", 5, null, null, null, ""],
    ["hear_r1000", 5, null, null, null, ""],
    ["hear_r2000", 0, null, null, null, ""],
    ["dental", null, "치석 · 치경부마모 · 치아 표면우식", null, null, ""],
    ["stress_res", 133.1, null, null, null, ""],
    ["ans_activity", 128.2, null, null, null, ""],
    ["ans_balance", 25.0, null, null, null, ""],
    ["age_real", 47, null, null, null, ""],
    ["age_health", 44, null, null, null, ""],
    ["age_target", 44, null, null, null, ""]
  ]') v
   WHERE e.kind = 'checkup' AND e.exam_date = '2019-08-08'
     AND e.user_id = (SELECT id FROM users WHERE role = 'admin' ORDER BY id LIMIT 1);

-- ══════════════════════════════════════════════════════════════════════
-- 2018-10-16 재검 — 종합검진이 아니라 석 달 뒤의 추적
-- ══════════════════════════════════════════════════════════════════════
INSERT OR IGNORE INTO health_exams (user_id, exam_date, kind, provider, title, memo, created_at, updated_at)
  SELECT id, '2018-10-16', 'checkup', '강북삼성병원 수원종합건진센터', '2018년 재검 (혈당 · 소변)',
         '7월 검진에서 공복혈당 108 · 당화혈색소 6.2 가 나와 석 달 뒤 다시 잰 회차. 혈당 100 · 당화혈색소 5.7 로 내려왔다. 그 둘과 소변검사뿐이라 항목이 적다.', datetime('now'), datetime('now')
    FROM users WHERE role = 'admin' ORDER BY id LIMIT 1;

INSERT OR IGNORE INTO health_results
  (user_id, exam_id, code, value_num, value_text, ref_low, ref_high, ref_text, created_at)
  SELECT e.user_id, e.id,
         json_extract(v.value, '$[0]'),
         json_extract(v.value, '$[1]'),
         COALESCE(json_extract(v.value, '$[2]'), ''),
         json_extract(v.value, '$[3]'),
         json_extract(v.value, '$[4]'),
         COALESCE(json_extract(v.value, '$[5]'), ''),
         datetime('now')
    FROM health_exams e,
         json_each('[
    ["glucose", 100, null, null, null, ""],
    ["hba1c", 5.7, null, null, null, ""],
    ["u_sg", 1.03, null, null, null, ""],
    ["u_ph", 5.5, null, null, null, ""],
    ["u_glucose", null, "음성", null, null, ""],
    ["u_ketone", null, "음성", null, null, ""],
    ["u_protein", null, "음성", null, null, ""],
    ["u_bilirubin", null, "음성", null, null, ""],
    ["u_urobilinogen", null, "약양성", null, null, ""],
    ["u_nitrite", null, "음성", null, null, ""],
    ["u_blood", null, "음성", null, null, ""],
    ["u_rbc", null, "0-1", null, null, ""],
    ["u_wbc", null, "0-1", null, null, ""],
    ["u_epi", null, "0-1", null, null, ""],
    ["u_leu", null, "음성", null, null, ""]
  ]') v
   WHERE e.kind = 'checkup' AND e.exam_date = '2018-10-16'
     AND e.user_id = (SELECT id FROM users WHERE role = 'admin' ORDER BY id LIMIT 1);

-- ══════════════════════════════════════════════════════════════════════
-- 2018-07-12 종합검진
-- ══════════════════════════════════════════════════════════════════════
INSERT OR IGNORE INTO health_exams (user_id, exam_date, kind, provider, title, memo, created_at, updated_at)
  SELECT id, '2018-07-12', 'checkup', '강북삼성병원 수원종합건진센터', '2018년 종합건강검진',
         '2021년 결과지의 비교 열에서 옮겨 적었다. 공복혈당 108 · 당화혈색소 6.2 로 이 기간 중 가장 높았던 해(석 달 뒤 재검에서 내려왔다). HDL 60 은 반대로 가장 높다. 요잠혈 약양성 · 비타민D 17.6 부족.', datetime('now'), datetime('now')
    FROM users WHERE role = 'admin' ORDER BY id LIMIT 1;

INSERT OR IGNORE INTO health_results
  (user_id, exam_id, code, value_num, value_text, ref_low, ref_high, ref_text, created_at)
  SELECT e.user_id, e.id,
         json_extract(v.value, '$[0]'),
         json_extract(v.value, '$[1]'),
         COALESCE(json_extract(v.value, '$[2]'), ''),
         json_extract(v.value, '$[3]'),
         json_extract(v.value, '$[4]'),
         COALESCE(json_extract(v.value, '$[5]'), ''),
         datetime('now')
    FROM health_exams e,
         json_each('[
    ["egd", null, "위축성위염 · 미란성위염", null, null, ""],
    ["occult", 0, "음성 (0)", null, null, ""],
    ["usg_pelvis", null, "정상 (전립선)", null, null, ""],
    ["afp", 2.9, null, null, null, ""],
    ["cea", 1.5, null, null, null, ""],
    ["psa", 0.821, null, null, null, ""],
    ["ca199", 6.7, null, null, null, ""],
    ["nse", 12.5, null, null, null, ""],
    ["cyfra", 0.9, null, null, null, ""],
    ["usg_abd", null, "정상", null, null, ""],
    ["tp", 7.2, null, null, null, ""],
    ["alb", 4.6, null, null, null, ""],
    ["glob", 2.6, null, null, null, ""],
    ["ag", 1.77, null, null, null, ""],
    ["ast", 19, null, null, null, ""],
    ["alt", 16, null, null, null, ""],
    ["alp", 49, null, null, null, ""],
    ["ggtp", 31, null, null, null, ""],
    ["tbil", 0.65, null, null, null, ""],
    ["dbil", 0.23, null, null, null, ""],
    ["idbil", 0.42, null, null, null, ""],
    ["hbsag", 0.3, "음성 (0.30)", null, null, ""],
    ["hbsab", 67.24, "양성 (67.24)", null, null, ""],
    ["hbcab", null, "양성", null, null, ""],
    ["hcvab", 0.04, "음성 (0.04)", null, null, ""],
    ["havab", null, "양성", null, null, ""],
    ["cxr", null, "정상", null, null, ""],
    ["fvc_l", 4.37, null, null, null, ""],
    ["fvc_p", 91, null, null, null, ""],
    ["fev1_l", 3.78, null, null, null, ""],
    ["fev1_p", 105, null, null, null, ""],
    ["fev1fvc", 87, null, null, null, ""],
    ["pef", 9.38, null, null, null, ""],
    ["cotinine", 0, "음성 (0)", null, null, ""],
    ["sbp", 106, null, null, null, ""],
    ["dbp", 58, null, null, null, ""],
    ["hr", 57, null, null, null, ""],
    ["ecg", null, "심실조기수축", null, null, ""],
    ["echo", null, "정상", null, null, ""],
    ["tchol", 202, null, null, null, ""],
    ["ldl", 147, null, null, null, ""],
    ["ldl_calc", 128, null, null, null, ""],
    ["hdl", 60, null, null, null, ""],
    ["tg", 71, null, null, null, ""],
    ["ldh", 175, null, null, null, ""],
    ["hscrp", 0.3, null, null, null, ""],
    ["apoa1", 139, null, null, null, ""],
    ["apob", 114, null, 63, 160, "63~160"],
    ["lpa_mg", 60.0, null, null, null, ""],
    ["homocysteine", 8.0, null, null, null, ""],
    ["pwv_r", 1052, null, 0, 1360, "0~1360"],
    ["pwv_l", 1007, null, 0, 1360, "0~1360"],
    ["abi_r", 1.15, null, null, null, ""],
    ["abi_l", 1.19, null, null, null, ""],
    ["glucose", 108, null, null, null, ""],
    ["hba1c", 6.2, null, null, null, ""],
    ["insulin", 6.7, null, null, null, ""],
    ["ft3", 3.45, null, null, null, ""],
    ["ft4", 1.33, null, null, null, ""],
    ["tsh", 1.76, null, null, null, ""],
    ["metabolic", null, "정상", null, null, ""],
    ["bun", 16.8, null, null, null, ""],
    ["creatinine", 1.0, null, null, null, ""],
    ["bc_ratio", 16.8, null, null, null, ""],
    ["egfr", 80, null, null, null, ""],
    ["u_sg", 1.025, null, null, null, ""],
    ["u_ph", 5.5, null, null, null, ""],
    ["u_glucose", null, "음성", null, null, ""],
    ["u_ketone", null, "음성", null, null, ""],
    ["u_protein", null, "음성", null, null, ""],
    ["u_bilirubin", null, "음성", null, null, ""],
    ["u_urobilinogen", null, "약양성", null, null, ""],
    ["u_nitrite", null, "음성", null, null, ""],
    ["u_blood", null, "약양성", null, null, ""],
    ["u_rbc", null, "3-5", null, null, ""],
    ["u_wbc", null, "0-1", null, null, ""],
    ["u_epi", null, "0-1", null, null, ""],
    ["u_leu", null, "음성", null, null, ""],
    ["uric_acid", 3.9, null, null, null, ""],
    ["calcium", 9.6, null, null, null, ""],
    ["phosphorus", 3.9, null, null, null, ""],
    ["sodium", 139, null, null, null, ""],
    ["potassium", 4.3, null, null, null, ""],
    ["magnesium", 2.2, null, null, null, ""],
    ["rbc", 4.57, null, null, null, ""],
    ["hb", 14.4, null, null, null, ""],
    ["hct", 42.2, null, null, null, ""],
    ["rdw", 12.6, null, null, null, ""],
    ["ferritin", 69.6, null, null, null, ""],
    ["iron", 129, null, null, null, ""],
    ["tibc", 327, null, null, null, ""],
    ["tsat", 39.45, null, null, null, ""],
    ["mcv", 92.3, null, null, null, ""],
    ["mch", 31.5, null, null, null, ""],
    ["mchc", 34.1, null, null, null, ""],
    ["platelet", 293, null, 160, 362, "160~362"],
    ["mpv", 10.0, null, null, null, ""],
    ["pdw", 11.2, null, null, null, ""],
    ["wbc", 5.87, null, null, null, ""],
    ["anc", 3.86, null, null, null, ""],
    ["neutrophil", 65.8, null, null, null, ""],
    ["eosinophil", 1.0, null, null, null, ""],
    ["basophil", 0.3, null, null, null, ""],
    ["lymphocyte", 25.7, null, null, null, ""],
    ["monocyte", 7.2, null, null, null, ""],
    ["eos_count", 58.7, null, null, null, ""],
    ["crp", 0.34, "음성 (0.34)", null, null, ""],
    ["rpr", null, "음성", null, null, ""],
    ["rf", null, "음성", null, null, ""],
    ["vitd", 17.6, null, null, null, ""],
    ["height", 174.6, null, null, null, ""],
    ["weight", 65.7, null, null, null, ""],
    ["bmi", 21.6, null, null, null, ""],
    ["waist", 80.7, null, null, null, ""],
    ["slm", 49.8, null, null, null, ""],
    ["fatmass", 13, null, null, null, ""],
    ["bodyfat", 19.8, null, null, null, ""],
    ["fatdist", 0.86, null, null, null, ""],
    ["eye_l", 0.8, null, null, null, ""],
    ["eye_r", 0.2, null, null, null, ""],
    ["iop_l", 13.5, null, null, null, ""],
    ["iop_r", 13, null, null, null, ""],
    ["fundus", null, "정상", null, null, ""],
    ["hear_l500", 5, null, null, null, ""],
    ["hear_l1000", 15, null, null, null, ""],
    ["hear_l2000", 10, null, null, null, ""],
    ["hear_r500", 5, null, null, null, ""],
    ["hear_r1000", 5, null, null, null, ""],
    ["hear_r2000", 5, null, null, null, ""],
    ["dental", null, "치아 표면우식 · 치석(치석제거필요)", null, null, ""],
    ["stress_res", 108.7, null, null, null, ""],
    ["ans_activity", 107.5, null, null, null, ""],
    ["ans_balance", 58.3, null, null, null, ""],
    ["age_real", 46, null, null, null, ""],
    ["age_health", 44, null, null, null, ""],
    ["age_target", 44, null, null, null, ""]
  ]') v
   WHERE e.kind = 'checkup' AND e.exam_date = '2018-07-12'
     AND e.user_id = (SELECT id FROM users WHERE role = 'admin' ORDER BY id LIMIT 1);

-- ══════════════════════════════════════════════════════════════════════
-- 2017-07 종합검진 — **그래프에서 옮겨 적은 회차**
-- ══════════════════════════════════════════════════════════════════════
-- 값 표에는 2018년까지만 있고, 2017년은 앞쪽 '연도별 주요건강 지표' 그래프에만
-- 남아 있다. 그래서 이 회차는 **그래프의 점 위에 적힌 숫자**를 옮긴 것이다.
--   · 그래프에 적힌 것은 'YYYY-MM' 까지다 — 날짜를 그 달 1일로 두었다.
--   · 2018년 것을 같은 그래프에서 읽어 값 표와 맞춰 보니 열 항목이 모두 일치했다.
--     그래서 2017년 것도 믿을 만하다고 보았다.
--   · 다만 표에서 온 다른 해보다 덜 정확하다. ALT 처럼 이름표가 다른 점에 가려
--     읽히지 않은 항목은 **적지 않았다** — 어림한 숫자를 넣느니 비워 둔다.
INSERT OR IGNORE INTO health_exams (user_id, exam_date, kind, provider, title, memo, created_at, updated_at)
  SELECT id, '2017-07-01', 'checkup', '강북삼성병원 수원종합건진센터', '2017년 종합건강검진 (그래프 발췌)',
         '값 표가 아니라 2021년 결과지 앞쪽의 연도별 그래프에서 옮겨 적은 열 항목. 날짜는 그래프에 적힌 2017-07 을 그 달 1일로 둔 것이라 실제 검진일과 다를 수 있다. γ-GTP 59 로 이 기간 중 가장 높다.', datetime('now'), datetime('now')
    FROM users WHERE role = 'admin' ORDER BY id LIMIT 1;

INSERT OR IGNORE INTO health_results
  (user_id, exam_id, code, value_num, value_text, ref_low, ref_high, ref_text, created_at)
  SELECT e.user_id, e.id,
         json_extract(v.value, '$[0]'),
         json_extract(v.value, '$[1]'),
         COALESCE(json_extract(v.value, '$[2]'), ''),
         json_extract(v.value, '$[3]'),
         json_extract(v.value, '$[4]'),
         COALESCE(json_extract(v.value, '$[5]'), ''),
         datetime('now')
    FROM health_exams e,
         json_each('[
    ["weight", 65, null, null, null, ""],
    ["sbp", 104, null, null, null, ""],
    ["dbp", 62, null, null, null, ""],
    ["ast", 17, null, null, null, ""],
    ["ggtp", 59, null, null, null, ""],
    ["tchol", 212, null, null, null, ""],
    ["ldl", 147, null, null, null, ""],
    ["hdl", 59, null, null, null, ""],
    ["tg", 76, null, null, null, ""],
    ["glucose", 103, null, null, null, ""]
  ]') v
   WHERE e.kind = 'checkup' AND e.exam_date = '2017-07-01'
     AND e.user_id = (SELECT id FROM users WHERE role = 'admin' ORDER BY id LIMIT 1);

-- ══════════════════════════════════════════════════════════════════════
-- 2021-09-16 인바디 — 검진 때 같이 잰 것
-- ══════════════════════════════════════════════════════════════════════
INSERT OR IGNORE INTO health_exams (user_id, exam_date, kind, provider, title, memo, created_at, updated_at)
  SELECT id, '2021-09-16', 'inbody', '강북삼성병원 수원종합건진센터 (InBody)', '인바디 (InBody 73점)',
         '적정체중 67.2kg · 체중조절 −0.5kg · 지방조절 −3.8kg · 근육조절 +3.3kg. 체지방률 20.5% 로 경도비만 판정.', datetime('now'), datetime('now')
    FROM users WHERE role = 'admin' ORDER BY id LIMIT 1;

INSERT OR IGNORE INTO health_results
  (user_id, exam_id, code, value_num, value_text, ref_low, ref_high, ref_text, created_at)
  SELECT e.user_id, e.id,
         json_extract(v.value, '$[0]'),
         json_extract(v.value, '$[1]'),
         COALESCE(json_extract(v.value, '$[2]'), ''),
         json_extract(v.value, '$[3]'),
         json_extract(v.value, '$[4]'),
         COALESCE(json_extract(v.value, '$[5]'), ''),
         datetime('now')
    FROM health_exams e,
         json_each('[
    ["height", 174.8, null, null, null, ""],
    ["weight", 67.7, null, 57.1, 77.3, "57.1~77.3"],
    ["bmi", 22.2, null, 18.5, 25.0, "18.5~25.0"],
    ["tbw", 39.5, null, null, null, ""],
    ["icw", 24.8, null, 23.4, 28.6, "23.4~28.6"],
    ["ecw_vol", 14.7, null, 14.4, 17.6, "14.4~17.6"],
    ["protein", 10.8, null, 10.2, 12.4, "10.2~12.4"],
    ["mineral_mass", 3.54, null, 3.5, 4.28, "3.50~4.28"],
    ["fatmass", 13.9, null, 8.1, 16.1, "8.1~16.1"],
    ["slm", 50.8, null, null, null, ""],
    ["ffm", 53.8, null, null, null, ""],
    ["smm", 30.3, null, null, null, ""],
    ["bodyfat", 20.5, null, 10.0, 20.0, "10.0~20.0"],
    ["fatdist", 0.86, null, 0.8, 0.9, "0.80~0.90"],
    ["vfa", 55.4, null, null, 100, "~100"],
    ["ecw", 0.372, null, 0.36, 0.39, "0.360~0.390"],
    ["bmr", 1533, null, 1489, 1737, "1489~1737"],
    ["obesity_deg", 100, null, 90, 110, "90~110"],
    ["inbody_score", 73, null, null, null, ""],
    ["arm_r", 2.84, null, null, null, ""],
    ["arm_r_p", 88.8, null, null, null, ""],
    ["arm_l", 2.85, null, null, null, ""],
    ["arm_l_p", 89.0, null, null, null, ""],
    ["trunk", 23.8, null, null, null, ""],
    ["trunk_p", 93.2, null, null, null, ""],
    ["leg_r", 8.77, null, null, null, ""],
    ["leg_r_p", 98.5, null, null, null, ""],
    ["leg_l", 8.8, null, null, null, ""],
    ["leg_l_p", 98.8, null, null, null, ""],
    ["target_weight", 67.2, null, null, null, ""],
    ["adj_weight", -0.5, null, null, null, ""],
    ["adj_fat", -3.8, null, null, null, ""],
    ["adj_muscle", 3.3, null, null, null, ""]
  ]') v
   WHERE e.kind = 'inbody' AND e.exam_date = '2021-09-16'
     AND e.user_id = (SELECT id FROM users WHERE role = 'admin' ORDER BY id LIMIT 1);
